using System.Collections.Generic;

namespace WpfAutoGitHelper.Localization
{
    /// <summary>Additional UI languages (merged over English at runtime).</summary>
    internal static class LocResourcesMore
    {
        public static Dictionary<string, string> CreateDe() => Pack(
            "Git ohne Terminal", "Einstellungen", "Sprache", "Design", "Hell", "Dunkel",
            "Vor Commit bestätigen", "Vor Verwerfen von Dateiänderungen bestätigen",
            "Status nach Speichern des Repos aktualisieren", "Einstellungen speichern", "Log leeren",
            "Repository", "Beliebiger Ordner mit .git-Verzeichnis",
            "Pfad zum Repo-Stamm oder zuletzt verwendeter Ordner", "Aktueller Branch:",
            "Durchsuchen…", "Speichern", "Ordner", "GitHub",
            "Ordner auf der Festplatte wählen", ".git prüfen, Pfad merken, Status aktualisieren",
            "Repo-Ordner im Explorer öffnen", "GitHub-Seite für origin öffnen",
            "Aktionen", "Was die Aktionen tun", "Beschäftigt: {0}",
            "Pull", "Status", "Diff", "Alle hinzufügen", "Commit", "Push",
            "Änderungen von origin holen (Rebase, dann Merge-Fallback)",
            "Branch, git status und Dateiliste anzeigen",
            "Diff für ausgewählte Datei oder gesamtes Arbeitsverzeichnis",
            "Alle Änderungen stagen (git add -A)",
            "Commit mit obiger Nachricht erstellen",
            "Aktuellen Branch zu origin pushen",
            "Pull — Remote-Commits laden und auf den aktuellen Branch anwenden.",
            "Status — Branch, Dateiliste und Log aktualisieren.",
            "Diff — Unstaged/Staged-Unterschiede anzeigen.",
            "Alle hinzufügen — alle geänderten und neuen Dateien stagen.",
            "Commit — gestagte Änderungen mit Ihrer Nachricht festhalten.",
            "Push — lokale Commits zum origin des aktuellen Branchs senden.",
            "Commit-Nachricht", "Branches", "Name für neuen lokalen Branch",
            "Lokale Branches in diesem Repository", "Erstellen", "Checkout", "Branch pushen",
            "Neuen Branch erstellen und wechseln (git checkout -b)",
            "Zum ausgewählten Branch wechseln",
            "Ausgewählten Branch pushen und Upstream setzen (-u origin)",
            "Git-Identität", "Nur dieses Repository (nicht --global)", "Laden", "Anwenden",
            "user.name und user.email aus git config lesen",
            "Name/E-Mail in lokale oder globale git config schreiben",
            "Geänderte Dateien", "Status", "Pfad", "Änderungen an ausgewählter Datei verwerfen",
            "Verfolgte Datei auf letzten Commit zurücksetzen (git restore)", "Log",
            "Ordner mit .git-Verzeichnis wählen",
            "Kein .git-Ordner — Wurzel des Git-Klons wählen.",
            "Repository-Pfad gespeichert: {0}",
            "GitHub-URL konnte nicht ermittelt werden (remote origin).",
            "Commit-Nachricht eingeben.",
            "Commit mit aktuell gestagten Änderungen erstellen?",
            "Commit", "Aktueller Branch konnte nicht ermittelt werden.",
            "Nicht verfolgte Dateien können hier nicht zurückgesetzt werden. Manuell löschen oder git clean.",
            "Änderungen an dieser Datei verwerfen?\n{0}", "Zurücksetzen",
            "user.name und user.email aus git config geladen.",
            "Für Repo-Einstellungen zuerst gültigen Pfad setzen und speichern.",
            "Name und/oder E-Mail eingeben.", "Namen für neuen Branch eingeben.", "Branch auswählen.",
            "Git nicht gefunden. Installieren: https://git-scm.com/download/win",
            "Aktualisierung beim Start fehlgeschlagen: {0}", "Einstellungen gespeichert.",
            "Kein gültiges Git-Repository.");

        public static Dictionary<string, string> CreateFr() => Pack(
            "Git sans terminal", "Paramètres", "Langue", "Thème", "Clair", "Sombre",
            "Confirmer avant le commit", "Confirmer avant d'annuler les modifications d'un fichier",
            "Actualiser le statut après enregistrement du dépôt", "Enregistrer les paramètres", "Effacer le journal",
            "Dépôt", "Tout dossier contenant un répertoire .git",
            "Chemin racine du dépôt ou dossier récent", "Branche actuelle :",
            "Parcourir…", "Enregistrer", "Dossier", "GitHub",
            "Choisir un dossier sur le disque", "Vérifier .git, mémoriser le chemin, actualiser le statut",
            "Ouvrir le dossier du dépôt dans l'Explorateur", "Ouvrir la page GitHub de origin",
            "Actions", "Rôle des actions", "Occupé : {0}",
            "Pull", "Statut", "Diff", "Tout ajouter", "Commit", "Push",
            "Récupérer et intégrer les changements depuis origin (rebase puis merge)",
            "Afficher la branche, git status et la liste des fichiers",
            "Afficher le diff du fichier sélectionné ou de tout l'arbre",
            "Indexer toutes les modifications (git add -A)",
            "Créer un commit avec le message ci-dessus",
            "Pousser la branche actuelle vers origin",
            "Pull — télécharger les commits distants et les appliquer à votre branche.",
            "Statut — actualiser la branche, la liste des fichiers et le journal.",
            "Diff — afficher les différences non indexées/indexées.",
            "Tout ajouter — indexer tous les fichiers modifiés et nouveaux.",
            "Commit — enregistrer les modifications indexées avec votre message.",
            "Push — envoyer les commits locaux vers origin sur la branche actuelle.",
            "Message de commit", "Branches", "Nom d'une nouvelle branche locale",
            "Branches locales de ce dépôt", "Créer", "Checkout", "Pousser la branche",
            "Créer et basculer vers une nouvelle branche (git checkout -b)",
            "Basculer vers la branche sélectionnée",
            "Pousser la branche sélectionnée et définir upstream (-u origin)",
            "Identité Git", "Ce dépôt uniquement (pas --global)", "Charger", "Appliquer",
            "Lire user.name et user.email depuis git config",
            "Écrire nom/e-mail dans git config local ou global",
            "Fichiers modifiés", "Statut", "Chemin", "Annuler les modifications du fichier sélectionné",
            "Restaurer le fichier suivi au dernier commit (git restore)", "Journal",
            "Sélectionnez un dossier contenant un répertoire .git",
            "Pas de dossier .git — choisissez la racine du clone Git.",
            "Chemin du dépôt enregistré : {0}",
            "Impossible de résoudre l'URL GitHub (remote origin).",
            "Saisissez un message de commit.",
            "Créer un commit avec les modifications indexées actuelles ?",
            "Commit", "Impossible de détecter la branche actuelle.",
            "Les fichiers non suivis ne peuvent pas être annulés ici. Supprimez-les ou utilisez git clean.",
            "Annuler les modifications de ce fichier ?\n{0}", "Annuler",
            "user.name et user.email chargés depuis git config.",
            "Pour les paramètres du dépôt, définissez et enregistrez d'abord un chemin valide.",
            "Saisissez un nom et/ou un e-mail.", "Saisissez le nom de la nouvelle branche.", "Sélectionnez une branche.",
            "Git introuvable. Installez : https://git-scm.com/download/win",
            "Échec de l'actualisation au démarrage : {0}", "Paramètres enregistrés.",
            "Dépôt Git non valide.");

        public static Dictionary<string, string> CreateEs() => Pack(
            "Git sin terminal", "Ajustes", "Idioma", "Tema", "Claro", "Oscuro",
            "Confirmar antes del commit", "Confirmar antes de descartar cambios en un archivo",
            "Actualizar estado tras guardar el repositorio", "Guardar ajustes", "Borrar registro",
            "Repositorio", "Cualquier carpeta con un directorio .git",
            "Ruta raíz del repositorio o carpeta reciente", "Rama actual:",
            "Examinar…", "Guardar", "Carpeta", "GitHub",
            "Elegir carpeta en el disco", "Validar .git, recordar ruta, actualizar estado",
            "Abrir carpeta del repositorio en el Explorador", "Abrir página de GitHub de origin",
            "Acciones", "Qué hace cada acción", "Ocupado: {0}",
            "Pull", "Estado", "Diff", "Añadir todo", "Commit", "Push",
            "Obtener e integrar cambios de origin (rebase y luego merge)",
            "Mostrar rama, git status y lista de archivos",
            "Mostrar diff del archivo seleccionado o de todo el árbol",
            "Preparar todos los cambios (git add -A)",
            "Crear commit con el mensaje de arriba",
            "Enviar la rama actual a origin",
            "Pull — descargar commits remotos y aplicarlos a su rama.",
            "Estado — actualizar rama, lista de archivos y registro.",
            "Diff — mostrar diferencias sin preparar/preparadas.",
            "Añadir todo — preparar todos los archivos modificados y nuevos.",
            "Commit — registrar cambios preparados con su mensaje.",
            "Push — subir commits locales a origin en la rama actual.",
            "Mensaje de commit", "Ramas", "Nombre de nueva rama local",
            "Ramas locales de este repositorio", "Crear", "Checkout", "Push de rama",
            "Crear y cambiar a nueva rama (git checkout -b)",
            "Cambiar a la rama seleccionada",
            "Enviar rama seleccionada y definir upstream (-u origin)",
            "Identidad Git", "Solo este repositorio (no --global)", "Cargar", "Aplicar",
            "Leer user.name y user.email de git config",
            "Escribir nombre/correo en git config local o global",
            "Archivos modificados", "Estado", "Ruta", "Descartar cambios del archivo seleccionado",
            "Restaurar archivo rastreado al último commit (git restore)", "Registro",
            "Seleccione una carpeta con directorio .git",
            "No hay carpeta .git — elija la raíz del clon Git.",
            "Ruta del repositorio guardada: {0}",
            "No se pudo resolver la URL de GitHub (remote origin).",
            "Introduzca un mensaje de commit.",
            "¿Crear commit con los cambios preparados actuales?",
            "Commit", "No se detectó la rama actual.",
            "Los archivos no rastreados no se revierten aquí. Elimínelos o use git clean.",
            "¿Descartar cambios en este archivo?\n{0}", "Revertir",
            "user.name y user.email cargados de git config.",
            "Para ajustes del repo, primero establezca y guarde una ruta válida.",
            "Introduzca nombre y/o correo.", "Introduzca nombre de la nueva rama.", "Seleccione una rama.",
            "Git no encontrado. Instale: https://git-scm.com/download/win",
            "Error al actualizar al iniciar: {0}", "Ajustes guardados.",
            "Repositorio Git no válido.");

        public static Dictionary<string, string> CreatePt() => Pack(
            "Git sem terminal", "Configurações", "Idioma", "Tema", "Claro", "Escuro",
            "Confirmar antes do commit", "Confirmar antes de descartar alterações do arquivo",
            "Atualizar status após salvar o repositório", "Salvar configurações", "Limpar log",
            "Repositório", "Qualquer pasta com diretório .git",
            "Caminho raiz do repositório ou pasta recente", "Branch atual:",
            "Procurar…", "Salvar", "Pasta", "GitHub",
            "Escolher pasta no disco", "Validar .git, lembrar caminho, atualizar status",
            "Abrir pasta do repositório no Explorer", "Abrir página GitHub do origin",
            "Ações", "O que fazem as ações", "Ocupado: {0}",
            "Pull", "Status", "Diff", "Adicionar tudo", "Commit", "Push",
            "Buscar e integrar alterações do origin (rebase e depois merge)",
            "Mostrar branch, git status e lista de arquivos",
            "Mostrar diff do arquivo selecionado ou da árvore inteira",
            "Preparar todas as alterações (git add -A)",
            "Criar commit com a mensagem acima",
            "Enviar branch atual para origin",
            "Pull — baixar commits remotos e aplicar ao branch atual.",
            "Status — atualizar branch, lista de arquivos e log.",
            "Diff — mostrar diferenças não preparadas/preparadas.",
            "Adicionar tudo — preparar todos os arquivos modificados e novos.",
            "Commit — registrar alterações preparadas com sua mensagem.",
            "Push — enviar commits locais ao origin no branch atual.",
            "Mensagem de commit", "Branches", "Nome do novo branch local",
            "Branches locais deste repositório", "Criar", "Checkout", "Push do branch",
            "Criar e mudar para novo branch (git checkout -b)",
            "Mudar para o branch selecionado",
            "Enviar branch selecionado e definir upstream (-u origin)",
            "Identidade Git", "Somente este repositório (não --global)", "Carregar", "Aplicar",
            "Ler user.name e user.email do git config",
            "Gravar nome/e-mail no git config local ou global",
            "Arquivos alterados", "Status", "Caminho", "Descartar alterações do arquivo selecionado",
            "Restaurar arquivo rastreado ao último commit (git restore)", "Log",
            "Selecione uma pasta com diretório .git",
            "Sem pasta .git — escolha a raiz do clone Git.",
            "Caminho do repositório salvo: {0}",
            "Não foi possível resolver URL do GitHub (remote origin).",
            "Digite uma mensagem de commit.",
            "Criar commit com as alterações preparadas atuais?",
            "Commit", "Não foi possível detectar o branch atual.",
            "Arquivos não rastreados não podem ser revertidos aqui. Exclua ou use git clean.",
            "Descartar alterações neste arquivo?\n{0}", "Reverter",
            "user.name e user.email carregados do git config.",
            "Para configurações do repo, defina e salve um caminho válido primeiro.",
            "Digite nome e/ou e-mail.", "Digite o nome do novo branch.", "Selecione um branch.",
            "Git não encontrado. Instale: https://git-scm.com/download/win",
            "Falha na atualização ao iniciar: {0}", "Configurações salvas.",
            "Repositório Git inválido.");

        public static Dictionary<string, string> CreatePl() => Pack(
            "Git bez terminala", "Ustawienia", "Język", "Motyw", "Jasny", "Ciemny",
            "Potwierdź przed commitem", "Potwierdź przed odrzuceniem zmian pliku",
            "Odśwież status po zapisaniu repozytorium", "Zapisz ustawienia", "Wyczyść log",
            "Repozytorium", "Dowolny folder z katalogiem .git",
            "Ścieżka do korzenia repozytorium lub ostatni folder", "Bieżąca gałąź:",
            "Przeglądaj…", "Zapisz", "Folder", "GitHub",
            "Wybierz folder na dysku", "Sprawdź .git, zapamiętaj ścieżkę, odśwież status",
            "Otwórz folder repozytorium w Eksploratorze", "Otwórz stronę GitHub origin",
            "Akcje", "Co robią akcje", "Zajęty: {0}",
            "Pull", "Status", "Diff", "Dodaj wszystko", "Commit", "Push",
            "Pobierz i scal zmiany z origin (rebase, potem merge)",
            "Pokaż gałąź, git status i listę plików",
            "Pokaż diff wybranego pliku lub całego drzewa",
            "Dodaj wszystkie zmiany do indeksu (git add -A)",
            "Utwórz commit z powyższą wiadomością",
            "Wyślij bieżącą gałąź do origin",
            "Pull — pobierz zdalne commity i zastosuj do gałęzi.",
            "Status — odśwież gałąź, listę plików i log.",
            "Diff — pokaż różnice unstaged/staged.",
            "Dodaj wszystko — dodaj wszystkie zmienione i nowe pliki.",
            "Commit — zapisz zmiany w indeksie z wiadomością.",
            "Push — wyślij lokalne commity do origin.",
            "Wiadomość commita", "Gałęzie", "Nazwa nowej gałęzi lokalnej",
            "Lokalne gałęzie tego repozytorium", "Utwórz", "Checkout", "Push gałęzi",
            "Utwórz i przełącz na nową gałąź (git checkout -b)",
            "Przełącz na wybraną gałąź",
            "Wyślij wybraną gałąź i ustaw upstream (-u origin)",
            "Tożsamość Git", "Tylko to repozytorium (nie --global)", "Wczytaj", "Zastosuj",
            "Odczytaj user.name i user.email z git config",
            "Zapisz imię/e-mail w lokalnym lub globalnym git config",
            "Zmienione pliki", "Status", "Ścieżka", "Odrzuć zmiany wybranego pliku",
            "Przywróć śledzony plik do ostatniego commita (git restore)", "Log",
            "Wybierz folder z katalogiem .git",
            "Brak folderu .git — wybierz korzeń klonu Git.",
            "Zapisano ścieżkę repozytorium: {0}",
            "Nie można ustalić URL GitHub (remote origin).",
            "Wprowadź wiadomość commita.",
            "Utworzyć commit z bieżącymi zmianami w indeksie?",
            "Commit", "Nie wykryto bieżącej gałęzi.",
            "Nieśledzone pliki nie są tu cofane. Usuń ręcznie lub użyj git clean.",
            "Odrzucić zmiany w tym pliku?\n{0}", "Cofnij",
            "Wczytano user.name i user.email z git config.",
            "Dla ustawień repo najpierw ustaw i zapisz poprawną ścieżkę.",
            "Wprowadź imię i/lub e-mail.", "Wprowadź nazwę nowej gałęzi.", "Wybierz gałąź.",
            "Nie znaleziono Git. Zainstaluj: https://git-scm.com/download/win",
            "Błąd odświeżania przy starcie: {0}", "Ustawienia zapisane.",
            "Nieprawidłowe repozytorium Git.");

        public static Dictionary<string, string> CreateIt() => Pack(
            "Git senza terminale", "Impostazioni", "Lingua", "Tema", "Chiaro", "Scuro",
            "Conferma prima del commit", "Conferma prima di annullare le modifiche al file",
            "Aggiorna stato dopo salvataggio repository", "Salva impostazioni", "Cancella log",
            "Repository", "Qualsiasi cartella con directory .git",
            "Percorso radice del repository o cartella recente", "Branch corrente:",
            "Sfoglia…", "Salva", "Cartella", "GitHub",
            "Scegli cartella su disco", "Verifica .git, memorizza percorso, aggiorna stato",
            "Apri cartella repository in Explorer", "Apri pagina GitHub di origin",
            "Azioni", "Cosa fanno le azioni", "Occupato: {0}",
            "Pull", "Stato", "Diff", "Aggiungi tutto", "Commit", "Push",
            "Recupera e integra modifiche da origin (rebase poi merge)",
            "Mostra branch, git status e elenco file",
            "Mostra diff del file selezionato o dell'intero albero",
            "Metti in stage tutte le modifiche (git add -A)",
            "Crea commit con il messaggio sopra",
            "Push del branch corrente su origin",
            "Pull — scarica commit remoti e applicali al branch.",
            "Stato — aggiorna branch, elenco file e log.",
            "Diff — mostra differenze non in stage/in stage.",
            "Aggiungi tutto — metti in stage tutti i file modificati e nuovi.",
            "Commit — registra le modifiche in stage con il messaggio.",
            "Push — invia commit locali a origin sul branch corrente.",
            "Messaggio di commit", "Branch", "Nome del nuovo branch locale",
            "Branch locali di questo repository", "Crea", "Checkout", "Push branch",
            "Crea e passa a nuovo branch (git checkout -b)",
            "Passa al branch selezionato",
            "Push del branch selezionato e imposta upstream (-u origin)",
            "Identità Git", "Solo questo repository (non --global)", "Carica", "Applica",
            "Leggi user.name e user.email da git config",
            "Scrivi nome/email in git config locale o globale",
            "File modificati", "Stato", "Percorso", "Annulla modifiche al file selezionato",
            "Ripristina file tracciato all'ultimo commit (git restore)", "Log",
            "Seleziona cartella con directory .git",
            "Nessuna cartella .git — scegli la radice del clone Git.",
            "Percorso repository salvato: {0}",
            "Impossibile risolvere URL GitHub (remote origin).",
            "Inserisci un messaggio di commit.",
            "Creare commit con le modifiche in stage attuali?",
            "Commit", "Impossibile rilevare il branch corrente.",
            "I file non tracciati non possono essere annullati qui. Elimina o usa git clean.",
            "Annullare le modifiche a questo file?\n{0}", "Annulla",
            "user.name e user.email caricati da git config.",
            "Per impostazioni repo, imposta e salva prima un percorso valido.",
            "Inserisci nome e/o email.", "Inserisci nome del nuovo branch.", "Seleziona un branch.",
            "Git non trovato. Installa: https://git-scm.com/download/win",
            "Aggiornamento all'avvio fallito: {0}", "Impostazioni salvate.",
            "Repository Git non valido.");

        public static Dictionary<string, string> CreateNl() => Pack(
            "Git zonder terminal", "Instellingen", "Taal", "Thema", "Licht", "Donker",
            "Bevestigen vóór commit", "Bevestigen vóór wijzigingen van bestand te verwerpen",
            "Status vernieuwen na opslaan repository", "Instellingen opslaan", "Log wissen",
            "Repository", "Elke map met een .git-map",
            "Pad naar repo-root of recente map", "Huidige branch:",
            "Bladeren…", "Opslaan", "Map", "GitHub",
            "Kies map op schijf", "Controleer .git, onthoud pad, vernieuw status",
            "Open repository-map in Verkenner", "Open GitHub-pagina van origin",
            "Acties", "Wat de acties doen", "Bezig: {0}",
            "Pull", "Status", "Diff", "Alles toevoegen", "Commit", "Push",
            "Haal wijzigingen op van origin (rebase, daarna merge)",
            "Toon branch, git status en bestandslijst",
            "Toon diff van geselecteerd bestand of hele werkmap",
            "Stage alle wijzigingen (git add -A)",
            "Maak commit met bovenstaand bericht",
            "Push huidige branch naar origin",
            "Pull — download remote commits en pas toe op branch.",
            "Status — vernieuw branch, bestandslijst en log.",
            "Diff — toon unstaged/staged verschillen.",
            "Alles toevoegen — stage alle gewijzigde en nieuwe bestanden.",
            "Commit — leg gestage wijzigingen vast met uw bericht.",
            "Push — upload lokale commits naar origin.",
            "Commitbericht", "Branches", "Naam voor nieuwe lokale branch",
            "Lokale branches in deze repository", "Maken", "Checkout", "Push branch",
            "Maak en wissel naar nieuwe branch (git checkout -b)",
            "Wissel naar geselecteerde branch",
            "Push geselecteerde branch en stel upstream in (-u origin)",
            "Git-identiteit", "Alleen deze repository (niet --global)", "Laden", "Toepassen",
            "Lees user.name en user.email uit git config",
            "Schrijf naam/e-mail naar lokale of globale git config",
            "Gewijzigde bestanden", "Status", "Pad", "Wijzigingen van geselecteerd bestand verwerpen",
            "Herstel gevolgd bestand naar laatste commit (git restore)", "Log",
            "Selecteer map met .git-map",
            "Geen .git-map — kies root van Git-kloon.",
            "Repositorypad opgeslagen: {0}",
            "Kon GitHub-URL niet bepalen (remote origin).",
            "Voer een commitbericht in.",
            "Commit maken met huidige gestage wijzigingen?",
            "Commit", "Kon huidige branch niet detecteren.",
            "Niet-gevolgde bestanden kunnen hier niet worden teruggedraaid. Verwijder of gebruik git clean.",
            "Wijzigingen in dit bestand verwerpen?\n{0}", "Terugdraaien",
            "user.name en user.email geladen uit git config.",
            "Stel eerst een geldig pad in en sla op voor repo-instellingen.",
            "Voer naam en/of e-mail in.", "Voer naam van nieuwe branch in.", "Selecteer een branch.",
            "Git niet gevonden. Installeer: https://git-scm.com/download/win",
            "Vernieuwen bij opstarten mislukt: {0}", "Instellingen opgeslagen.",
            "Geen geldige Git-repository.");

        public static Dictionary<string, string> CreateTr() => Pack(
            "Terminal olmadan Git", "Ayarlar", "Dil", "Tema", "Açık", "Koyu",
            "Commit öncesi onayla", "Dosya değişikliklerini iptal etmeden önce onayla",
            "Depo kaydedildikten sonra durumu yenile", "Ayarları kaydet", "Günlüğü temizle",
            "Depo", ".git dizini olan herhangi bir klasör",
            "Depo kök yolu veya son kullanılan klasör", "Geçerli dal:",
            "Gözat…", "Kaydet", "Klasör", "GitHub",
            "Diskten klasör seç", ".git doğrula, yolu hatırla, durumu yenile",
            "Depo klasörünü Gezgin'de aç", "origin için GitHub sayfasını aç",
            "İşlemler", "İşlemlerin açıklaması", "Meşgul: {0}",
            "Pull", "Durum", "Diff", "Tümünü ekle", "Commit", "Push",
            "origin'den değişiklikleri al ve birleştir (rebase, sonra merge)",
            "Dal, git status ve dosya listesini göster",
            "Seçili dosya veya tüm ağaç için diff göster",
            "Tüm değişiklikleri stage'e al (git add -A)",
            "Yukarıdaki mesajla commit oluştur",
            "Geçerli dalı origin'e push et",
            "Pull — uzak commit'leri indir ve dala uygula.",
            "Durum — dal, dosya listesi ve günlüğü yenile.",
            "Diff — staged/unstaged farkları göster.",
            "Tümünü ekle — tüm değişen ve yeni dosyaları stage'e al.",
            "Commit — stage'deki değişiklikleri mesajla kaydet.",
            "Push — yerel commit'leri origin'e gönder.",
            "Commit mesajı", "Dallar", "Yeni yerel dal adı",
            "Bu depodaki yerel dallar", "Oluştur", "Checkout", "Dal push",
            "Yeni dal oluştur ve geç (git checkout -b)",
            "Seçili dala geç",
            "Seçili dalı push et ve upstream ayarla (-u origin)",
            "Git kimliği", "Yalnızca bu depo (--global değil)", "Yükle", "Uygula",
            "git config'den user.name ve user.email oku",
            "Ad/e-postayı yerel veya global git config'e yaz",
            "Değişen dosyalar", "Durum", "Yol", "Seçili dosyanın değişikliklerini iptal et",
            "İzlenen dosyayı son commit'e döndür (git restore)", "Günlük",
            ".git dizini olan klasör seçin",
            ".git yok — Git klonunun kökünü seçin.",
            "Depo yolu kaydedildi: {0}",
            "GitHub URL'si çözülemedi (remote origin).",
            "Commit mesajı girin.",
            "Mevcut stage değişiklikleriyle commit oluşturulsun mu?",
            "Commit", "Geçerli dal algılanamadı.",
            "İzlenmeyen dosyalar burada geri alınamaz. Silin veya git clean kullanın.",
            "Bu dosyadaki değişiklikler iptal edilsin mi?\n{0}", "Geri al",
            "user.name ve user.email git config'den yüklendi.",
            "Depo ayarları için önce geçerli yolu ayarlayıp kaydedin.",
            "Ad ve/veya e-posta girin.", "Yeni dal adı girin.", "Bir dal seçin.",
            "Git bulunamadı. Kurun: https://git-scm.com/download/win",
            "Başlangıç yenilemesi başarısız: {0}", "Ayarlar kaydedildi.",
            "Geçerli Git deposu değil.");

        public static Dictionary<string, string> CreateZh() => Pack(
            "无需终端的 Git 操作", "设置", "语言", "主题", "浅色", "深色",
            "提交前确认", "丢弃文件更改前确认",
            "保存仓库后刷新状态", "保存设置", "清空日志",
            "仓库", "任何包含 .git 目录的文件夹",
            "仓库根路径或最近使用的文件夹", "当前分支：",
            "浏览…", "保存", "文件夹", "GitHub",
            "选择磁盘上的文件夹", "验证 .git、记住路径、刷新状态",
            "在资源管理器中打开仓库文件夹", "打开 origin 的 GitHub 页面",
            "操作", "操作说明", "忙碌：{0}",
            "Pull", "状态", "Diff", "全部添加", "提交", "Push",
            "从 origin 获取并合并更改（rebase，然后 merge）",
            "显示分支、git status 和文件列表",
            "显示所选文件或整个工作树的 diff",
            "暂存所有更改 (git add -A)",
            "使用上方消息创建提交",
            "将当前分支推送到 origin",
            "Pull — 下载远程提交并应用到当前分支。",
            "状态 — 刷新分支、文件列表和日志。",
            "Diff — 显示未暂存/已暂存的差异。",
            "全部添加 — 暂存所有修改和新建的文件。",
            "提交 — 用您的消息记录已暂存的更改。",
            "Push — 将本地提交上传到 origin 的当前分支。",
            "提交消息", "分支", "新本地分支名称",
            "此仓库的本地分支", "创建", "检出", "推送分支",
            "创建并切换到新分支 (git checkout -b)",
            "切换到所选分支",
            "推送所选分支并设置上游 (-u origin)",
            "Git 身份", "仅此仓库（非 --global）", "加载", "应用",
            "从 git config 读取 user.name 和 user.email",
            "将姓名/邮箱写入本地或全局 git config",
            "已更改的文件", "状态", "路径", "丢弃所选文件的更改",
            "将跟踪的文件恢复到最后一次提交 (git restore)", "日志",
            "选择包含 .git 目录的文件夹",
            "此处没有 .git — 请选择 Git 克隆的根目录。",
            "已保存仓库路径：{0}",
            "无法解析 GitHub URL（remote origin）。",
            "请输入提交消息。",
            "使用当前已暂存的更改创建提交？",
            "提交", "无法检测当前分支。",
            "未跟踪的文件无法在此恢复。请手动删除或使用 git clean。",
            "丢弃此文件的更改？\n{0}", "还原",
            "已从 git config 加载 user.name 和 user.email。",
            "仓库设置请先设置并保存有效路径。",
            "请输入姓名和/或邮箱。", "请输入新分支名称。", "请选择分支。",
            "未找到 Git。请安装：https://git-scm.com/download/win",
            "启动时刷新失败：{0}", "设置已保存。",
            "不是有效的 Git 仓库。");

        public static Dictionary<string, string> CreateJa() => Pack(
            "ターミナル不要の Git 操作", "設定", "言語", "テーマ", "ライト", "ダーク",
            "コミット前に確認", "ファイル変更の破棄前に確認",
            "リポジトリ保存後にステータスを更新", "設定を保存", "ログをクリア",
            "リポジトリ", ".git ディレクトリを含む任意のフォルダ",
            "リポジトリのルートパスまたは最近のフォルダ", "現在のブランチ:",
            "参照…", "保存", "フォルダ", "GitHub",
            "ディスク上のフォルダを選択", ".git を確認しパスを記憶、ステータスを更新",
            "エクスプローラーでリポジトリフォルダを開く", "origin の GitHub ページを開く",
            "操作", "操作の説明", "処理中: {0}",
            "Pull", "ステータス", "Diff", "すべて追加", "コミット", "Push",
            "origin から変更を取得して統合（rebase、失敗時は merge）",
            "ブランチ、git status、ファイル一覧を表示",
            "選択ファイルまたは全体の diff を表示",
            "すべての変更をステージ (git add -A)",
            "上のメッセージでコミットを作成",
            "現在のブランチを origin に push",
            "Pull — リモートのコミットを取得してブランチに適用。",
            "ステータス — ブランチ、ファイル一覧、ログを更新。",
            "Diff — 未ステージ/ステージ済みの差分を表示。",
            "すべて追加 — 変更・新規ファイルをすべてステージ。",
            "コミット — ステージ済みの変更をメッセージ付きで記録。",
            "Push — ローカルコミットを origin に送信。",
            "コミットメッセージ", "ブランチ", "新しいローカルブランチ名",
            "このリポジトリのローカルブランチ", "作成", "チェックアウト", "ブランチを push",
            "新しいブランチを作成して切り替え (git checkout -b)",
            "選択したブランチに切り替え",
            "選択ブランチを push して upstream を設定 (-u origin)",
            "Git ID", "このリポジトリのみ（--global ではない）", "読み込み", "適用",
            "git config から user.name と user.email を読み込み",
            "名前/メールをローカルまたはグローバル git config に書き込み",
            "変更されたファイル", "状態", "パス", "選択ファイルの変更を破棄",
            "追跡ファイルを最後のコミットに復元 (git restore)", "ログ",
            ".git ディレクトリを含むフォルダを選択",
            ".git がありません — Git クローンのルートを選択してください。",
            "リポジトリパスを保存しました: {0}",
            "GitHub URL を解決できませんでした (remote origin)。",
            "コミットメッセージを入力してください。",
            "現在ステージ済みの変更でコミットを作成しますか？",
            "コミット", "現在のブランチを検出できませんでした。",
            "未追跡ファイルはここでは元に戻せません。削除するか git clean を使用してください。",
            "このファイルの変更を破棄しますか？\n{0}", "元に戻す",
            "git config から user.name と user.email を読み込みました。",
            "リポジトリ設定は先に有効なパスを設定して保存してください。",
            "名前および/またはメールを入力してください。", "新しいブランチ名を入力してください。", "ブランチを選択してください。",
            "Git が見つかりません。インストール: https://git-scm.com/download/win",
            "起動時の更新に失敗しました: {0}", "設定を保存しました。",
            "有効な Git リポジトリではありません。");

        public static Dictionary<string, string> CreateKo() => Pack(
            "터미널 없이 Git 작업", "설정", "언어", "테마", "라이트", "다크",
            "커밋 전 확인", "파일 변경 취소 전 확인",
            "저장소 저장 후 상태 새로고침", "설정 저장", "로그 지우기",
            "저장소", ".git 디렉터리가 있는 모든 폴더",
            "저장소 루트 경로 또는 최근 폴더", "현재 브랜치:",
            "찾아보기…", "저장", "폴더", "GitHub",
            "디스크에서 폴더 선택", ".git 확인, 경로 기억, 상태 새로고침",
            "탐색기에서 저장소 폴더 열기", "origin의 GitHub 페이지 열기",
            "작업", "작업 설명", "처리 중: {0}",
            "Pull", "상태", "Diff", "모두 추가", "커밋", "Push",
            "origin에서 변경 사항 가져와 통합(rebase 후 merge)",
            "브랜치, git status, 파일 목록 표시",
            "선택한 파일 또는 전체 diff 표시",
            "모든 변경 사항 스테이징 (git add -A)",
            "위 메시지로 커밋 생성",
            "현재 브랜치를 origin에 push",
            "Pull — 원격 커밋을 다운로드해 현재 브랜치에 적용.",
            "상태 — 브랜치, 파일 목록, 로그 새로고침.",
            "Diff — 스테이징/비스테이징 차이 표시.",
            "모두 추가 — 수정·새 파일을 모두 스테이징.",
            "커밋 — 스테이징된 변경을 메시지와 함께 기록.",
            "Push — 로컬 커밋을 origin에 업로드.",
            "커밋 메시지", "브랜치", "새 로컬 브랜치 이름",
            "이 저장소의 로컬 브랜치", "만들기", "체크아웃", "브랜치 push",
            "새 브랜치 생성 및 전환 (git checkout -b)",
            "선택한 브랜치로 전환",
            "선택 브랜치 push 및 upstream 설정 (-u origin)",
            "Git 신원", "이 저장소만 (--global 아님)", "불러오기", "적용",
            "git config에서 user.name, user.email 읽기",
            "이름/이메일을 로컬 또는 전역 git config에 쓰기",
            "변경된 파일", "상태", "경로", "선택 파일 변경 취소",
            "추적 파일을 마지막 커밋으로 복원 (git restore)", "로그",
            ".git 디렉터리가 있는 폴더 선택",
            ".git 없음 — Git 클론 루트를 선택하세요.",
            "저장소 경로 저장됨: {0}",
            "GitHub URL을 확인할 수 없습니다 (remote origin).",
            "커밋 메시지를 입력하세요.",
            "현재 스테이징된 변경으로 커밋을 만드시겠습니까?",
            "커밋", "현재 브랜치를 감지할 수 없습니다.",
            "추적되지 않은 파일은 여기서 되돌릴 수 없습니다. 삭제하거나 git clean을 사용하세요.",
            "이 파일의 변경을 취소하시겠습니까?\n{0}", "되돌리기",
            "git config에서 user.name, user.email을 불러왔습니다.",
            "저장소 설정은 먼저 유효한 경로를 설정하고 저장하세요.",
            "이름 및/또는 이메일을 입력하세요.", "새 브랜치 이름을 입력하세요.", "브랜치를 선택하세요.",
            "Git을 찾을 수 없습니다. 설치: https://git-scm.com/download/win",
            "시작 시 새로고침 실패: {0}", "설정이 저장되었습니다.",
            "유효한 Git 저장소가 아닙니다.");

        public static Dictionary<string, string> CreateCs() => Pack(
            "Git bez terminálu", "Nastavení", "Jazyk", "Motiv", "Světlý", "Tmavý",
            "Potvrdit před commitem", "Potvrdit před zrušením změn souboru",
            "Obnovit stav po uložení repozitáře", "Uložit nastavení", "Vymazat log",
            "Repozitář", "Jakákoli složka s adresářem .git",
            "Cesta ke kořeni repozitáře nebo poslední složka", "Aktuální větev:",
            "Procházet…", "Uložit", "Složka", "GitHub",
            "Vybrat složku na disku", "Ověřit .git, zapamatovat cestu, obnovit stav",
            "Otevřít složku repozitáře v Průzkumníku", "Otevřít stránku GitHub pro origin",
            "Akce", "Co dělají akce", "Zaneprázdněno: {0}",
            "Pull", "Stav", "Diff", "Přidat vše", "Commit", "Push",
            "Stáhnout a sloučit změny z origin (rebase, pak merge)",
            "Zobrazit větev, git status a seznam souborů",
            "Zobrazit diff vybraného souboru nebo celého stromu",
            "Přidat všechny změny do indexu (git add -A)",
            "Vytvořit commit se zprávou výše",
            "Odeslat aktuální větev na origin",
            "Pull — stáhnout vzdálené commity a použít na větev.",
            "Stav — obnovit větev, seznam souborů a log.",
            "Diff — zobrazit unstaged/staged rozdíly.",
            "Přidat vše — přidat všechny změněné a nové soubory.",
            "Commit — zaznamenat změny v indexu se zprávou.",
            "Push — odeslat lokální commity na origin.",
            "Zpráva commitu", "Větve", "Název nové lokální větve",
            "Lokální větve tohoto repozitáře", "Vytvořit", "Checkout", "Push větve",
            "Vytvořit a přepnout na novou větev (git checkout -b)",
            "Přepnout na vybranou větev",
            "Odeslat vybranou větev a nastavit upstream (-u origin)",
            "Git identita", "Pouze tento repozitář (ne --global)", "Načíst", "Použít",
            "Načíst user.name a user.email z git config",
            "Zapsat jméno/e-mail do lokálního nebo globálního git config",
            "Změněné soubory", "Stav", "Cesta", "Zrušit změny vybraného souboru",
            "Obnovit sledovaný soubor na poslední commit (git restore)", "Log",
            "Vyberte složku s adresářem .git",
            "Zde není .git — zvolte kořen Git klonu.",
            "Cesta repozitáře uložena: {0}",
            "Nelze určit URL GitHub (remote origin).",
            "Zadejte zprávu commitu.",
            "Vytvořit commit s aktuálními změnami v indexu?",
            "Commit", "Nelze zjistit aktuální větev.",
            "Nesledované soubory zde nelze vrátit. Smažte je nebo použijte git clean.",
            "Zrušit změny v tomto souboru?\n{0}", "Vrátit",
            "Načteno user.name a user.email z git config.",
            "Pro nastavení repozitáře nejprve nastavte a uložte platnou cestu.",
            "Zadejte jméno a/nebo e-mail.", "Zadejte název nové větve.", "Vyberte větev.",
            "Git nenalezen. Nainstalujte: https://git-scm.com/download/win",
            "Obnovení při startu selhalo: {0}", "Nastavení uloženo.",
            "Neplatný Git repozitář.");

        private static Dictionary<string, string> Pack(
            string appSubtitle, string settingsHeader, string settingsLanguage, string settingsTheme,
            string themeLight, string themeDark, string settingsConfirmCommit, string settingsConfirmRestore,
            string settingsAutoRefresh, string btnSaveSettings, string btnClearLog,
            string repoHeader, string repoHint, string repoPathTip, string repoCurrentBranch,
            string btnBrowse, string btnSaveRepo, string btnOpenFolder, string btnOpenGitHub,
            string tipBrowse, string tipSaveRepo, string tipOpenFolder, string tipOpenGitHub,
            string actionsHeader, string actionsHelpHeader, string busyFormat,
            string btnPull, string btnStatus, string btnDiff, string btnAddAll, string btnCommit, string btnPush,
            string tipPull, string tipStatus, string tipDiff, string tipAddAll, string tipCommit, string tipPush,
            string helpPull, string helpStatus, string helpDiff, string helpAddAll, string helpCommit, string helpPush,
            string commitHeader, string branchesHeader, string branchesNewTip, string branchesListTip,
            string btnCreateBranch, string btnCheckout, string btnPushBranch,
            string tipCreateBranch, string tipCheckout, string tipPushBranch,
            string identityHeader, string identityLocalOnly, string btnLoadConfig, string btnApplyConfig,
            string tipLoadConfig, string tipApplyConfig,
            string filesHeader, string filesColStatus, string filesColPath, string btnRestoreFile, string tipRestoreFile,
            string logHeader, string dlgFolderBrowse, string msgNoGitFolder, string msgSavedRepo, string msgNoGitHub,
            string msgEnterCommit, string msgConfirmCommit, string dlgCommit, string msgNoBranch, string msgUntrackedRestore,
            string msgConfirmRestore, string dlgRestore, string msgLoadedConfig, string msgNeedRepoForLocal,
            string msgEnterNameEmail, string msgEnterBranchName, string msgSelectBranch, string msgGitNotFound,
            string msgStartupRefreshFailed, string msgSettingsSaved, string msgNoValidRepo)
        {
            return new Dictionary<string, string>
            {
                ["AppSubtitle"] = appSubtitle,
                ["Settings_Header"] = settingsHeader,
                ["Settings_Language"] = settingsLanguage,
                ["Settings_Theme"] = settingsTheme,
                ["Theme_Light"] = themeLight,
                ["Theme_Dark"] = themeDark,
                ["Settings_ConfirmCommit"] = settingsConfirmCommit,
                ["Settings_ConfirmRestore"] = settingsConfirmRestore,
                ["Settings_AutoRefresh"] = settingsAutoRefresh,
                ["Btn_SaveSettings"] = btnSaveSettings,
                ["Btn_ClearLog"] = btnClearLog,
                ["Repo_Header"] = repoHeader,
                ["Repo_Hint"] = repoHint,
                ["Repo_PathTip"] = repoPathTip,
                ["Repo_CurrentBranch"] = repoCurrentBranch,
                ["Btn_Browse"] = btnBrowse,
                ["Btn_SaveRepo"] = btnSaveRepo,
                ["Btn_OpenFolder"] = btnOpenFolder,
                ["Btn_OpenGitHub"] = btnOpenGitHub,
                ["Tip_Browse"] = tipBrowse,
                ["Tip_SaveRepo"] = tipSaveRepo,
                ["Tip_OpenFolder"] = tipOpenFolder,
                ["Tip_OpenGitHub"] = tipOpenGitHub,
                ["Actions_Header"] = actionsHeader,
                ["Actions_HelpHeader"] = actionsHelpHeader,
                ["Busy_Format"] = busyFormat,
                ["Btn_Pull"] = btnPull,
                ["Btn_Status"] = btnStatus,
                ["Btn_Diff"] = btnDiff,
                ["Btn_AddAll"] = btnAddAll,
                ["Btn_Commit"] = btnCommit,
                ["Btn_Push"] = btnPush,
                ["Tip_Pull"] = tipPull,
                ["Tip_Status"] = tipStatus,
                ["Tip_Diff"] = tipDiff,
                ["Tip_AddAll"] = tipAddAll,
                ["Tip_Commit"] = tipCommit,
                ["Tip_Push"] = tipPush,
                ["Help_Pull"] = helpPull,
                ["Help_Status"] = helpStatus,
                ["Help_Diff"] = helpDiff,
                ["Help_AddAll"] = helpAddAll,
                ["Help_Commit"] = helpCommit,
                ["Help_Push"] = helpPush,
                ["Commit_Header"] = commitHeader,
                ["Branches_Header"] = branchesHeader,
                ["Branches_NewTip"] = branchesNewTip,
                ["Branches_ListTip"] = branchesListTip,
                ["Btn_CreateBranch"] = btnCreateBranch,
                ["Btn_Checkout"] = btnCheckout,
                ["Btn_PushBranch"] = btnPushBranch,
                ["Tip_CreateBranch"] = tipCreateBranch,
                ["Tip_Checkout"] = tipCheckout,
                ["Tip_PushBranch"] = tipPushBranch,
                ["Identity_Header"] = identityHeader,
                ["Identity_LocalOnly"] = identityLocalOnly,
                ["Btn_LoadConfig"] = btnLoadConfig,
                ["Btn_ApplyConfig"] = btnApplyConfig,
                ["Tip_LoadConfig"] = tipLoadConfig,
                ["Tip_ApplyConfig"] = tipApplyConfig,
                ["Files_Header"] = filesHeader,
                ["Files_ColStatus"] = filesColStatus,
                ["Files_ColPath"] = filesColPath,
                ["Btn_RestoreFile"] = btnRestoreFile,
                ["Tip_RestoreFile"] = tipRestoreFile,
                ["Log_Header"] = logHeader,
                ["Dlg_FolderBrowse"] = dlgFolderBrowse,
                ["Msg_NoGitFolder"] = msgNoGitFolder,
                ["Msg_SavedRepo"] = msgSavedRepo,
                ["Msg_NoGitHub"] = msgNoGitHub,
                ["Msg_EnterCommit"] = msgEnterCommit,
                ["Msg_ConfirmCommit"] = msgConfirmCommit,
                ["Dlg_Commit"] = dlgCommit,
                ["Msg_NoBranch"] = msgNoBranch,
                ["Msg_UntrackedRestore"] = msgUntrackedRestore,
                ["Msg_ConfirmRestore"] = msgConfirmRestore,
                ["Dlg_Restore"] = dlgRestore,
                ["Msg_LoadedConfig"] = msgLoadedConfig,
                ["Msg_NeedRepoForLocal"] = msgNeedRepoForLocal,
                ["Msg_EnterNameEmail"] = msgEnterNameEmail,
                ["Msg_EnterBranchName"] = msgEnterBranchName,
                ["Msg_SelectBranch"] = msgSelectBranch,
                ["Msg_GitNotFound"] = msgGitNotFound,
                ["Msg_StartupRefreshFailed"] = msgStartupRefreshFailed,
                ["Msg_SettingsSaved"] = msgSettingsSaved,
                ["Msg_NoValidRepo"] = msgNoValidRepo,
            };
        }
    }
}
